### ISSUE TITLE
Entanglement does not support python 3.10

### ISSUE THREAD

**Issue by kdienes** [Hadron/entanglement#4]
I tried building using this Containerfile:

```
FROM debian:buster
RUN apt-get update
RUN apt-get -y install git dpkg-dev debhelper dh-python python3-all python3-openssl python3-setuptools python3-alembic python3-pytest-runner python3-iso8601 nodejs node-websocket python3-tornado python3-sh python3-pytest python3-sqlalchemy
RUN git clone https://github.com/Hadron/entanglement
RUN cd entanglement && dpkg-buildpackage -b -us -uc
```
This fails in TestBandwidth::testBasic and then hangs (instead of timing out to a FAIL).

The issue seems to be that the asyncio server gets EAGAIN from accept() and then resets the connection.

I tried a simpler test case and got similar behavior from this self-contained script:

```
import ssl, asyncio

class MockProto(asyncio.Protocol):

    def __init__(self):
        pass

    def data_received(self, data):
        print('data_received', data)
        pass

    def connection_lost(self, exc):
        print('connection_lost', exc)
        pass

    def eof_received(self):
        print('eof_received')
        return False

    def connection_made(self, transport):
        print('connection_made', transport)
        transport.write(b'connection_made')

loop = asyncio.new_event_loop()

server = loop.create_server(lambda : MockProto(), host='0.0.0.0', port=12345, reuse_port=True, reuse_address=True, start_serving=True)
server = loop.run_until_complete(server)

loop.run_until_complete(asyncio.sleep(3600))

```

**Comment by hartmans** [comment]
There appear to be multiple things going on here:

* The certs were expired.  I think that's what broke things on buster.
* Python 3.10 is more picky about how you set up ssl contexts, and so the server side of all ssl protocols was failing during initialization when python tried to wrap the socket.  This made the tests fail.  I don't actually know how to catch this error in any useful way.
* There appear to be a host of other python 3.10/bookworm issues to fix.  For example certhash_from_file is failing claiming that something  doesn't support the buffer api and needs to.  I just need to finish slogging through these.

What's the priority for bookworm/python3.10 support?
