### ISSUE TITLE
Integrate internal docs on Entanglement hooks

### ISSUE THREAD

**Issue by hartmans** [Hadron/entanglement#5]
@hadronjeff  pointed me at an internal page in his Hadron gitlab with a good summary of hook calling order for things like should_send and should_listen.
We should integrate that into the Entanglement docs.
`raw/master/knowledge/entanglement-hooks.md`
in Jeff's internal playground repo

**Comment by hadronjeff** [comment]
I have made a pull request with updated documentation: https://github.com/Hadron/entanglement/pull/6
